title: Elixir Curitiba
description: Evento sobre Elixir e linguagens do ecossistema de Erlang em Curitiba
url: "https://curitiba.elixiremfoco.com"
lang: pt-BR

social:
  name: Elixir Curitiba
  links:
    - https://curitiba.elixiremfoco.com

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: pages-themes/cayman@v0.2.0